name: VersionColorNK
api: "1.0.0"
author: Creadores Program
description: In old versions change the modern colors to the old Minecraft colors in chat
main: org.CreadoresProgram.VersionColorNK.Main
version: "1.1.0"